BetWorldCup/Models/BetViewModels/Bet.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BetWorldCup.Models.BetViewModels
{
    public class Bet
    {
        [Required]
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int BetId { get; set; }


        public int HomeScore { get; set; }

        public int AwayScore { get; set; }

        public virtual ResultType Result { get; set; }

        public virtual BetResult BetResult { get; set; }

        public virtual ApplicationUser User { get; set; }

        public virtual Match Match { get; set; }
    }
}

BetWorldCup/Models/BetViewModels/Match.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BetWorldCup.Models.BetViewModels
{
    public class Match
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int MatchId { get; set; }

        [Required]
        [DisplayName("Mnożnik")]
        [DefaultValue(1)]
        public int Multiplier { get; set; }

        [Required]
        [DisplayName("Data rozpoczęcia meczu")]
        public DateTime StartDate { get; set; }
        
        [Required]
        public int LeagueId { get; set; }

        [DefaultValue(false)]
        [DisplayName("Zakończony")]
        public bool IsFinished { get; set; }

        public int HomeScore { get; set; }

        public int AwayScore { get; set; }
        
        [Required]
        public virtual Team HomeTeam { get; set; }

        [Required]
        public virtual Team AwayTeam { get; set; }


        public virtual ResultType Result { get; set; }

        public virtual ICollection<Bet> Bets { get; set; }
    }
}

BetWorldCup/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using BetWorldCup.Models.BetViewModels;
using BetWorldCup.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using NToastNotify;

namespace BetWorldCup.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        private readonly IHomeService _homeService;
        private readonly IToastNotification _toastNotification;
        private readonly ILogger<HomeController> _logger;

        public HomeController(IHomeService homeService, IToastNotification toastNotification, ILogger<HomeController> logger)
        {
            _homeService = homeService;
            _toastNotification = toastNotification;
            _logger = logger;
        }

        #region Widoki
        
        public IActionResult Index()
        {
            IEnumerable<Match> model = new List<Match>();

            try
            {
                model = _homeService.GetMatchesForStartScreen();
            }
            catch (Exception e)
            {
                _toastNotification.AddErrorToastMessage("Nie udało się pobrać meczy, spróbuj ponownie!",
                    new ToastrOptions {Title = "Błąd!"});
                _logger.LogError(e, "Nie udało się pobrać meczy. Strona startowa.");
            }

            return View(model);
        }

        [Route("wszystkie-mecze")]
        public IActionResult AllMatches()
        {
            IEnumerable<Match> model = new List<Match>();

            try
            {
                model = _homeService.GetAllMatches().ToArray();
                var closest = model.OrderBy(p => Math.Abs((p.StartDate - DateTime.Now).Ticks)).First();
                ViewBag.DivId = $"{closest.HomeTeam.ShortName}-{closest.AwayTeam.ShortName}";
            }
            catch (Exception e)
            {
                _toastNotification.AddErrorToastMessage("Nie udało się pobrać meczy, spróbuj ponownie!",
                    new ToastrOptions { Title = "Błąd!" });
                _logger.LogError(e, "Nie udało się pobrać meczy. Wszystkie mecze.");
            }

            return View(model.OrderBy(p => p.StartDate));
        }

        [Route("mecz")]
        public IActionResult SingleMatch(int id)
        {
            var model = new Match();

            try
            {
                model = _homeService.GetSingleMatch(id);
            }
            catch (Exception e)
            {
                _toastNotification.AddErrorToastMessage("Nie udało się pobrać meczu, spróbuj ponownie!",
                    new ToastrOptions { Title = "Błąd!" });
                _logger.LogError(e, "Nie udało się pobrać meczu. Strona startowa.");
            }

            return View(model);
        }

        #endregion

        #region Akcje

        [Route("obstaw")]
        public JsonResult PlaceBet(Bet model, int matchId)
        {
            try
            {
                var bet = _homeService.PlaceBet(model, User.Identity.Name, matchId);
                return Json(new { ok = true, betId = bet.BetId });
            }
            catch (Exception e)
            {
                _logger.LogError(e, "Nie udało się obstawić.");
                return Json(new { ok = false, message = "Nie udało się obstawić. Spróbuj ponownie." });
            }
        }

        #endregion
    }
}

BetWorldCup/Controllers/StatsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using BetWorldCup.Models;
using BetWorldCup.Models.StatsViewModels;
using BetWorldCup.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using NToastNotify;

namespace BetWorldCup.Controllers
{
    [Authorize]
    public class StatsController : Controller
    {
        private readonly IStatsService _statsService;
        private readonly IToastNotification _toastNotification;
        private readonly ILogger<StatsController> _logger;
        private readonly IGoogleAnalyticsApiService _googleAnalyticsApiService;

        public StatsController(IStatsService statsService,
            IToastNotification toastNotification,
            ILogger<StatsController> logger,
            IGoogleAnalyticsApiService googleAnalyticsApiService)
        {
            _statsService = statsService;
            _toastNotification = toastNotification;
            _logger = logger;
            _googleAnalyticsApiService = googleAnalyticsApiService;
        }

        #region Widoki
        
        [Route("statystyki-uzytkownika")]
        public IActionResult UserData(string user)
        {
            var model = new ApplicationUser();

            try
            {
                model = _statsService.GetUserByName(user);

                ViewBag.Scores = _statsService.GetUserScoreHits(model, DateTime.Now);
                ViewBag.Results = _statsService.GetUserResultHits(model, DateTime.Now);
                ViewBag.Missess = _statsService.GetUserMisses(model, DateTime.Now);
                ViewBag.NoBets = _statsService.GetUserNoBets(model, DateTime.Now);
            }
            catch (Exception e)
            {
                _toastNotification.AddErrorToastMessage("Nie udało się pobrać użytkownika, spróbuj ponownie!",
                    new ToastrOptions { Title = "Błąd!" });
                _logger.LogError(e, "Nie udało się pobrać użytkownika. UserData - statystyki");
            }

            return View(model);
        }
        
        [Route("statystyki")]
        public IActionResult ResultAllStats()
        {
            return View();
        }

        [Route("druzyna")]
        public IActionResult TeamData(int teamId)
        {
            try
            {
                var model = _statsService.GetTeam(teamId);
                var matches = _statsService.GetTeamMatches(teamId).OrderBy(p => p.StartDate).ToList();
                ViewBag.Matches = matches;
                ViewBag.Table = _statsService.GetTable(matches.OrderBy(p => p.StartDate).First().LeagueId);
                return View(model);
            }
            catch (Exception e)
            {
                _toastNotification.AddErrorToastMessage("Nie udało się pobrać danych drużyny, spróbuj ponownie!",
                    new ToastrOptions { Title = "Błąd!" });
                _logger.LogError(e, "Nie udało się pobrać danych drużyny. TeamData - statystyki");
            }
            return View();
        }
        #endregion

        #region Tabele

        public IActionResult MatchResultTable(int matchId)
        {
            IEnumerable<UserMatchResult> model = new List<UserMatchResult>();

            try
            {
                model = _statsService.GetUserMatchResults(matchId, User.Identity.Name);
            }
            catch (Exception e)
            {
                _toastNotification.AddErrorToastMessage("Nie udało się pobrać tabeli wyników meczy, spróbuj ponownie!",
                    new ToastrOptions { Title = "Błąd!" });
                _logger.LogError(e, "Nie udało się pobrać tabeli wyników meczy. MatchResultTable - statystyki");
            }

            return PartialView("Tables/_SingleMatchBets", model);
        }
        
        public IActionResult FullClassificationTable(bool overflow = false)
        {
            IEnumerable<ClassificationRow> model = new List<ClassificationRow>();

            try
            {
                model = _statsService.GetActuallFullClassification(User.Identity.Name);
                ViewBag.Overflow = overflow ? " table-sidebar" : "";
            }
            catch (Exception e)
            {
                _toastNotification.AddErrorToastMessage("Nie udało się pobrać klasyfikacji, spróbuj ponownie!",
                    new ToastrOptions { Title = "Błąd!" });
                _logger.LogError(e, "Nie udało się pobrać klasyfikacji. FullClassificationTable - statystyki");
            }
            
            return PartialView("Tables/_FullClassification", model);
        }
        
        public IActionResult TopScoreClassificationTable()
        {
            IEnumerable<ClassificationRow> model = new List<ClassificationRow>();

            try
            {
                model = _statsService.GetAllUserScoreHits();
            }
            catch (Exception e)
            {
                _toastNotification.AddErrorToastMessage("Nie udało się pobrać klasyfikacji najwięcej trafień, spróbuj ponownie!",
                    new ToastrOptions { Title = "Błąd!" });
                _logger.LogError(e, "Nie udało się pobrać klasyfikacji. TopScoreClassificationTable - statystyki");
            }
            return PartialView("Tables/_TopFiveClassifictaion", model);
        }

        public IActionResult TopResultClassificationTable()
        {
            IEnumerable<ClassificationRow> model = new List<ClassificationRow>();
            try
            {
                model = _statsService.GetAllUserResulHits();
            }
            catch (Exception e)
            {
                _toastNotification.AddErrorToastMessage("Nie udało się pobrać klasyfikacji najwięcej rezultatów, spróbuj ponownie!",
                    new ToastrOptions { Title = "Błąd!" });
                _logger.LogError(e, "Nie udało się pobrać klasyfikacji. TopResultClassificationTable - statystyki");
            }
            return PartialView("Tables/_TopFiveClassifictaion", model);
        }

        public IActionResult TopMissesClassificationTable()
        {
            IEnumerable<ClassificationRow> model = new List<ClassificationRow>();
            try
            {
                model = _statsService.GetAllUserMisses();
            }
            catch (Exception e)
            {
                _toastNotification.AddErrorToastMessage("Nie udało się pobrać klasyfikacji błędnych rezultatów, spróbuj ponownie!",
                    new ToastrOptions { Title = "Błąd!" });
                _logger.LogError(e, "Nie udało się pobrać klasyfikacji. TopMissesClassificationTable - statystyki");
            }
            return PartialView("Tables/_TopFiveClassifictaion", model);
        }
        
        public IActionResult TopMatchesTable()
        {
            IEnumerable<ClassificationRow> model = new List<ClassificationRow>();
            try
            {
                model = _statsService.GetBestMatches();
            }
            catch (Exception e)
            {
                _toastNotification.AddErrorToastMessage("Nie udało się pobrać klasyfikacji najlepszych meczów, spróbuj ponownie!",
                    new ToastrOptions { Title = "Błąd!" });
                _logger.LogError(e, "Nie udało się pobrać klasyfikacji. TopMatches - statystyki");
            }
            return PartialView("Tables/_TopMatches", model);
        }

        public IActionResult WorstMatchesTable()
        {
            IEnumerable<ClassificationRow> model = new List<ClassificationRow>();
            try
            {
                model = _statsService.GetWorstMatches();
            }
            catch (Exception e)
            {
                _toastNotification.AddErrorToastMessage("Nie udało się pobrać klasyfikacji najgorszych meczów, spróbuj ponownie!",
                    new ToastrOptions { Title = "Błąd!" });
                _logger.LogError(e, "Nie udało się pobrać klasyfikacji. WorstMatches - statystyki");
            }
            return PartialView("Tables/_TopMatches", model);
        }

        public IActionResult TopTeamsTable()
        {
            IEnumerable<ClassificationRow> model = new List<ClassificationRow>();
            try
            {
                model = _statsService.GetBestTeams();
            }
            catch (Exception e)
            {
                _toastNotification.AddErrorToastMessage("Nie udało się pobrać klasyfikacji najlepszych drużyn, spróbuj ponownie!",
                    new ToastrOptions { Title = "Błąd!" });
                _logger.LogError(e, "Nie udało się pobrać klasyfikacji. TopTeamsTable - statystyki");
            }
            return PartialView("Tables/_TopTeams", model);
        }

        public IActionResult WorstTeamsTable()
        {
            IEnumerable<ClassificationRow> model = new List<ClassificationRow>();
            try
            {
                model = _statsService.GetWorstTeams();
            }
            catch (Exception e)
            {
                _toastNotification.AddErrorToastMessage("Nie udało się pobrać klasyfikacji najgorszych drużyn, spróbuj ponownie!",
                    new ToastrOptions { Title = "Błąd!" });
                _logger.LogError(e, "Nie udało się pobrać klasyfikacji. WorstTeamsTable - statystyki");
            }
            return PartialView("Tables/_TopTeams", model);
        }
        
        #endregion

        #region Wykresy

        [HttpPost]
        public JsonResult PieChartMatchResultRatio(int matchId)
        {
            try
            {
                var chartData = _statsService.PieChartMatchResultRatio(matchId);
                return Json(new { ok = true, chData = chartData });
            }
            catch (Exception e)
            {
                _logger.LogError(e, "Nie udało się pobrać danych do wykresu: PieChartMatchResultRatio.");

BetWorldCup/Views/Home/Partials/_Match.cshtml
@using BetWorldCup.Enum
@model BetWorldCup.Models.BetViewModels.Match

@{
    var homeLogo = Url.Content($"~/img/flags/{Model.HomeTeam.ShortName}.jpg");
    var awayLogo = Url.Content($"~/img/flags/{Model.AwayTeam.ShortName}.jpg");
    var bet = Model.Bets.FirstOrDefault(p => p.User.Email == User.Identity.Name);
    var matchState = Model.StartDate > DateTime.Now ? MatchStateEnum.Future : Model.StartDate.AddHours(2) > DateTime.Now ? MatchStateEnum.Present : MatchStateEnum.Past;
}


<section class="dashboard-counts padding-10">
    <div id="@Model.HomeTeam.ShortName-@Model.AwayTeam.ShortName" class="container-fluid">
        <div class="row bg-white has-shadow hidden-sm-down">
            <!-- Item -->
            <div class="col-md-3">
                <div class="item d-flex align-items-center h-100">
                    <img src="@homeLogo" class="img-flag" alt="" />
                    <div class="title">
                        <span class="title--left">
                            <a asp-controller="Stats" asp-action="TeamData" asp-route-teamId="@Model.HomeTeam.TeamId">
                                @Model.HomeTeam.LongName
                            </a>
                        </span>
                    </div>
                </div>
                @if (Model.HomeTeam.Multiplier != 1)
                {
                    <span data-toggle="tooltip"
                          data-placement="bottom"
                          title="Punkty tej drużyny mnożymy x@(Model.HomeTeam.Multiplier)!"
                          class="badge bg-green badge-corner badge-custom home">x@(Model.HomeTeam.Multiplier)</span>
                }
            </div>
            <div class="col-md-3">
                @if (matchState == MatchStateEnum.Future)
                {
                    <div class="item d-flex align-items-center h-50">
                        <div class="title w-85 text-center">
                            <span>Data rozpoczęcia meczu:</span>
                        </div>
                    </div>
                    <div class="item d-flex align-items-center h-50">
                        <div class="title w-85 text-center">
                            <span class="text-bold">@Model.StartDate.ToString("MMM dd, HH:mm")</span>
                        </div>
                    </div>
                }
                else
                {
                    <div class="item d-flex align-items-center h-50">
                        <div class="title w-85 text-center">
                            <span>Wynik -</span><span class="text-bold">&nbsp;@Model.StartDate.ToString("MMM dd, HH:mm")</span>
                        </div>
                    </div>
                    <div class="item d-flex align-items-center h-50">
                        <div class="number w-85 text-center">
                            <strong>
                                <a asp-controller="Home" asp-action="SingleMatch" asp-route-id="@Model.MatchId">
                                    @Model.HomeScore : @Model.AwayScore
                                </a>
                            </strong>
                        </div>
                    </div>
                }
                @if (Model.Multiplier != 1)
                {
                    <span data-toggle="tooltip"
                          data-placement="bottom"
                          title="Punkty za ten mecz mnożymy x@(Model.Multiplier)!"
                          class="badge bg-orange badge-corner badge-custom home">x@(Model.Multiplier)</span>
                }
            </div>
            <div class="col-md-3 col-md-3--only-screen-768">
                @Html.Partial("~/Views/Home/Partials/_Bet.cshtml", bet, new ViewDataDictionary(ViewData) { { "MatchState", matchState }, { "MatchId", Model.MatchId }, { "MatchMultiplier", Model.Multiplier * Model.HomeTeam.Multiplier * Model.AwayTeam.Multiplier }, { "SmUp", "" } })
            </div>
            <div class="col-md-3">
                <div class="item d-flex align-items-center h-100 pull-right">
                    <div class="title">
                        <span class="title--right">
                            <a asp-controller="Stats" asp-action="TeamData" asp-route-teamId="@Model.AwayTeam.TeamId">
                                @Model.AwayTeam.LongName
                            </a>
                        </span>
                    </div>
                    <img src="@awayLogo" class="img-flag" alt="" />
                </div>
                @if (Model.AwayTeam.Multiplier != 1)
                {
                    <span data-toggle="tooltip" 
                          data-placement="bottom" 
                          title="Punkty tej drużyny mnożymy x@(Model.AwayTeam.Multiplier)!" 
                          class="badge bg-green badge-corner badge-custom away">x@(Model.AwayTeam.Multiplier)</span>
                }
            </div>
        </div>
        <div class="row bg-white has-shadow hidden-sm-up">
            <!-- Item -->
            <div class="col">
                <div class="d-flex align-items-center align-content-center">
                    <div class="col-md-3">
                        <div class="item d-flex align-items-center">
                            <div class="title">
                                <span>
                                    <a asp-controller="Stats" asp-action="TeamData" asp-route-teamId="@Model.HomeTeam.TeamId">
                                        @Model.HomeTeam.LongName
                                    </a>
                                </span>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="item d-flex align-items-center">
                            <div class="title">
                                <span>
                                    <a asp-controller="Stats" asp-action="TeamData" asp-route-teamId="@Model.AwayTeam.TeamId">
                                        @Model.AwayTeam.LongName
                                    </a>
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="d-flex align-items-center align-content-center">
                    <div class="col-md-3">
                        <img src="@homeLogo" class="img-flag center" alt="" />
                    </div>
                    <div class="col-md-3">
                        <img src="@awayLogo" class="img-flag center" alt="" />
                    </div>
                </div>
            </div>
            <div class="col-md-3">
                @if (matchState == MatchStateEnum.Future)
                {
                    <div class="item d-flex align-items-center h-50 align-content-center">
                        <div class="title w-85 text-center">
                            <span>Data rozpoczęcia meczu:</span>
                        </div>
                    </div>
                    <div class="item d-flex align-items-center h-50">
                        <div class="title w-100 text-center">
                            <span class="text-bold">@Model.StartDate.ToString("MMM dd, HH:mm")</span>
                        </div>
                    </div>
                }
                else
                {
                    <div class="item d-flex align-items-center h-50 align-content-center">
                        <div class="title w-85 text-center">
                            <span>Wynik -</span><span class="text-bold">&nbsp;@Model.StartDate.ToString("MMM dd, HH:mm")</span>
                        </div>
                    </div>
                    <div class="item d-flex align-items-center h-50">
                        <div class="number w-100 text-center">
                            <strong>
                                <a asp-controller="Home" asp-action="SingleMatch" asp-route-id="@Model.MatchId">
                                    @Model.HomeScore : @Model.AwayScore
                                </a>
                            </strong>
                        </div>
                    </div>
                }
            </div>
            <div class="col-md-3">
                @Html.Partial("~/Views/Home/Partials/_Bet.cshtml", bet, new ViewDataDictionary(ViewData) { { "MatchState", matchState }, { "MatchId", Model.MatchId }, { "MatchMultiplier", Model.Multiplier * Model.HomeTeam.Multiplier * Model.AwayTeam.Multiplier }, {"SmUp", "-sm-up"} })
            </div>
        </div>
    </div>
</section>

<script>
    $(function() {
        if ($("#@Model.MatchId-form-place-bet-HomeScore").val() === "")
            $("#@Model.MatchId-form-place-bet-HomeScore").val(0);
        if ($("#@Model.MatchId-form-place-bet-AwayScore").val() === "")
            $("#@Model.MatchId-form-place-bet-AwayScore").val(0);
        if ($("#@Model.MatchId-form-place-bet-HomeScore-sm-up").val() === "")
            $("#@Model.MatchId-form-place-bet-HomeScore-sm-up").val(0);
        if ($("#@Model.MatchId-form-place-bet-AwayScore-sm-up").val() === "")
            $("#@Model.MatchId-form-place-bet-AwayScore-sm-up").val(0);

        $("#@Model.MatchId-place-bet").on("click",
            function (e) {
                e.preventDefault();

                var $this = $(this);


                if (StartPosting($this)) {

                    var url = '@Url.Action("PlaceBet", "Home")',
                        data = {
                            BetId: $("#@Model.MatchId-form-place-bet-BetId").val(),
                            HomeScore: $("#@Model.MatchId-form-place-bet-HomeScore").val(),
                            AwayScore: $("#@Model.MatchId-form-place-bet-AwayScore").val()
                        };

                    $.ajax({
                        url: url,
                        type: "POST",
                        cache: false,
                        data: {
                            model: data,
                            matchId: @Model.MatchId
                        },
                        success: function (result) {
                            if (result.ok) {
                                $("#@Model.MatchId-form-place-bet-BetId").val(result.betId);
                                if ($("#@Model.MatchId-no-bet") != undefined) {
                                    $("#@Model.MatchId-no-bet").remove();
                                    $("#@Model.MatchId-your-bet").removeClass("h-25");
                                    $("#@Model.MatchId-your-bet").addClass("h-50");
                                }
                                PostingSuccess($this);
                            } else {
                                PostingError($this);
                                ShowToaster(result.message, "error");
                            }
                        },
                        error : function() {
                            PostingError($this);
                            ShowToaster("Wystąpił nieoczekiwany wyjątek!", "error");
                        }
                    });
                }
            });

        $("#@Model.MatchId-place-bet-sm-up").on("click",
            function (e) {
                e.preventDefault();

                var $this = $(this);


                if (StartPosting($this)) {

                    var url = '@Url.Action("PlaceBet", "Home")',
                        data = {
                            BetId: $("#@Model.MatchId-form-place-bet-BetId-sm-up").val(),
                            HomeScore: $("#@Model.MatchId-form-place-bet-HomeScore-sm-up").val(),
                            AwayScore: $("#@Model.MatchId-form-place-bet-AwayScore-sm-up").val()
                        };

                    $.ajax({
                        url: url,
                        type: "POST",
                        cache: false,
                        data: {
                            model: data,
                            matchId: @Model.MatchId
                        },
                        success: function (result) {
                            if (result.ok) {
                                $("#@Model.MatchId-form-place-bet-BetId-sm-up").val(result.betId);
                                if ($("#@Model.MatchId-no-bet-sm-up") != undefined) {
                                    $("#@Model.MatchId-no-bet-sm-up").remove();
                                    $("#@Model.MatchId-your-bet-sm-up").removeClass("h-25");
                                    $("#@Model.MatchId-your-bet-sm-up").addClass("h-50");
                                }
                                PostingSuccess($this);
                            } else {
                                PostingError($this);
                                ShowToaster(result.message, "error");
                            }
                        },
                        error : function() {
                            PostingError($this);
                            ShowToaster("Wystąpił nieoczekiwany wyjątek!", "error");
                        }
                    });
                }
            });
    });
</script>

BetWorldCup/Views/Home/Partials/_SingleBet.cshtml
@model BetWorldCup.Models.BetViewModels.Bet

@{
    var matchId = ViewBag.MatchId;
    var smUp = ViewBag.SmUp;
}

<form id="@matchId-form-place-bet@(smUp)" class="form-inline">
    <input id="@matchId-form-place-bet-BetId@(smUp)" type="hidden" asp-for="BetId"/>
    <div class="d-inline-flex justify-content-center justify-content-center--margin-left">
        <div class="btn-group-vertical">
            <span class="add-home-@matchId btn-add-remove"><i class="fa fa-plus"></i></span>
            <span class="remove-home-@matchId btn-add-remove"><i class="fa fa-minus"></i></span>
        </div>
        <input id="@matchId-form-place-bet-HomeScore@(smUp)" type="number" asp-for="HomeScore" min="0" class="form-numeric w-25" />
        <div class="text-numeric"><strong> : </strong></div>
        <input id="@matchId-form-place-bet-AwayScore@(smUp)" type="number" asp-for="AwayScore" min="0" class="form-numeric w-25" />
        <div class="text-numeric"></div>
        <div class="btn-group-vertical btn-away-group">
            <span class="add-away-@matchId btn-add-remove"><i class="fa fa-plus"></i></span>
            <span class="remove-away-@matchId btn-add-remove"><i class="fa fa-minus"></i></span>
        </div>
        <button id="@matchId-place-bet@(smUp)" type="submit" class="s-btn"><i class="fa fa-save"></i></button>
    </div>
</form>

<script>
    $(document).ready(function () {

        var addHome = $('.add-home-@matchId');
        var minusHome = $('.remove-home-@matchId');
        var addAway = $('.add-away-@matchId');
        var minusAway = $('.remove-away-@matchId');
        var inputHome = $('#@matchId-form-place-bet-HomeScore@(smUp)');
        var inputAway = $('#@matchId-form-place-bet-AwayScore@(smUp)');
        var inputHome_val = inputHome.val();
        var inputAway_val = inputAway.val();

        addHome.click(function () {
            inputHome_val++;
            inputHome.val(inputHome_val);
        });
        minusHome.click(function () {
            if (inputHome.val() > 0) {
                inputHome_val--;
                inputHome.val(inputHome_val);
            }
        });

        addAway.click(function () {
            inputAway_val++;
            inputAway.val(inputAway_val);
        });
        minusAway.click(function () {
            if (inputAway.val() > 0) {
                inputAway_val--;
                inputAway.val(inputAway_val);
            }
        });
    });
</script>