BetWorldCup/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using BetWorldCup.Models;
using BetWorldCup.Models.BetViewModels;
using BetWorldCup.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;
using NToastNotify;

namespace BetWorldCup.Controllers
{
    [Authorize(Roles = "ADMIN")]
    [Route("panel-administratora")]
    public class AdminController : Controller
    {
        private readonly IAdminService _adminService;
        private readonly IStatsService _statsService;
        private readonly IToastNotification _toastNotification;
        private readonly ILogger<AdminController> _logger;

        public AdminController(IAdminService adminService, 
            IStatsService statsService, 
            IToastNotification toastNotification, 
            ILogger<AdminController> logger)
        {
            _adminService = adminService;
            _statsService = statsService;
            _toastNotification = toastNotification;
            _logger = logger;
        }

        #region Widoki
        
        [Route("wyniki")]
        public IActionResult Index()
        {
            IEnumerable<Match> model = new List<Match>();

            try
            {
                model = _adminService.GetMatchesForStartScreen();
            }
            catch (Exception e)
            {
                _toastNotification.AddErrorToastMessage("Nie udało się pobrać meczy, spróbuj ponownie!",
                    new ToastrOptions { Title = "Błąd!" });
                _logger.LogError(e, "Nie udało się pobrać meczy. Index - panel administratora.");
            }

            return View(model);
        }

        [Route("mecze")]
        public IActionResult ListOfMatches()
        {
            IEnumerable<Match> model = new List<Match>();

            try
            {
                if (TempData["Message"] != null)
                {
                    if (TempData["Message"].ToString() == "WARNING")
                        _toastNotification.AddWarningToastMessage("Nie można usunąć meczu, ponieważ są już do niego przypisane zakłady.",
                            new ToastrOptions { Title = "Ostrzeżenie!" });
                    else
                        _toastNotification.AddErrorToastMessage("Nie udało się usunąć meczu.",
                            new ToastrOptions { Title = "Błąd!" });
                }

                ViewBag.Teams = _adminService.GetNotEliminatedTeams().Select(p => new SelectListItem
                {
                    Text = $"{p.ShortName} - {p.LongName}",
                    Value = p.TeamId.ToString()
                }).OrderBy(p => p.Text);

                model = _adminService.GetMatchesForAdminModify();
            }
            catch (Exception e)
            {
                _toastNotification.AddErrorToastMessage("Nie udało się pobrać meczy, spróbuj ponownie!",
                    new ToastrOptions { Title = "Błąd!" });
                _logger.LogError(e, "Nie udało się pobrać meczy. ListOfMatches - panel administratora.");
            }

            return View(model);
        }

        [Route("druzyny")]
        public IActionResult Teams()
        {
            IEnumerable<Team> model = new List<Team>();

            try
            {
                model = _adminService.GetTeams();
            }
            catch (Exception e)
            {
                _toastNotification.AddErrorToastMessage("Nie udało się pobrać drużyn, spróbuj ponownie!",
                    new ToastrOptions { Title = "Błąd!" });
                _logger.LogError(e, "Nie udało się pobrać drużyn. Teams - panel administratora.");
            }

            return View(model);
        }

        [Route("uzytkownicy")]
        public IActionResult Users()
        {
            IEnumerable<ApplicationUser> model = new List<ApplicationUser>();

            try
            {
                model = _adminService.GetUsers();
            }
            catch (Exception e)
            {
                _toastNotification.AddErrorToastMessage("Nie udało się pobrać użytkowników, spróbuj ponownie!",
                    new ToastrOptions { Title = "Błąd!" });
                _logger.LogError(e, "Nie udało się pobrać użytkowników. Users - panel administratora.");
            }

            return View(model);
        }
        
        [Route("usuwanie-uzytkownikow")]
        public IActionResult DeleteUsers()
        {
            IEnumerable<ApplicationUser> model = new List<ApplicationUser>();

            try
            {
                model = _adminService.GetUsers();
            }
            catch (Exception e)
            {
                _toastNotification.AddErrorToastMessage("Nie udało się pobrać użytkowników, spróbuj ponownie!",
                    new ToastrOptions { Title = "Błąd!" });
                _logger.LogError(e, "Nie udało się pobrać użytkowników. Users - panel administratora.");
            }

            return View(model);
        }

        [Route("statystyki-google")]
        public IActionResult GoogleAnalytics()
        {
            return View();
        }
        #endregion

        #region Akcje

        [Route("aktualizuj-wynik")]
        public IActionResult UpdateScore(Match model)
        {
            try
            {
                _adminService.UpdateMatchScore(model);
                _statsService.UpdateUserPointsAndPositions(model.StartDate);

                return Json(new { ok = true });
            }
            catch (Exception e)
            {
                _logger.LogError(e, "Nie udało się zaktualizować wyniku.");
                return Json(new { ok = false, message = "Nie udało się zaktualizować wyniku. Spróbuj ponownie." });
            }
        }
        
        [Route("dodaj-mecz")]
        public IActionResult PostNewMatch(Match model, int homeId, int awayId)
        {
            try
            {
                model.StartDate = model.StartDate.AddSeconds(-model.StartDate.Second);
                model.StartDate = model.StartDate.AddMilliseconds(-model.StartDate.Millisecond);
                model.HomeTeam = _adminService.GetTeamById(homeId);
                model.AwayTeam = _adminService.GetTeamById(awayId);

                _adminService.AddMatch(model);
                return Json(new { ok = true });
            }
            catch (Exception e)
            {
                _logger.LogError(e, "Nie udało się dodać nowego meczu.");
                return Json(new { ok = false, message = "Nie udało się dodać nowego meczu. Spróbuj ponownie." });
            }
        }
        
        [Route("usun-mecz")]
        public IActionResult DeleteMatch(int id)
        {
            try
            {
                var match = _adminService.GetMatch(id);
                if (match.Bets.Any())
                {
                    TempData["Message"] = "WARNING";
                    return RedirectToAction("ListOfMatches");
                }

                _adminService.DeleteMatch(id);
                TempData["Message"] = null;
                return RedirectToAction("ListOfMatches");
            }
            catch (Exception e)
            {
                _logger.LogError(e, "Nie udało się usunąć meczu. DeleteMatch - panel administratora.");
                TempData["Message"] = "ERROR";
                return RedirectToAction("ListOfMatches");
            }
        }
        
        [Route("aktualizuj-status-wyeliminowany")]
        public IActionResult UpdateEliminatedStatus(Team model)
        {
            try
            {
                _adminService.UpdateEliminatedStatus(model);
                return Json(new { ok = true });
            }
            catch (Exception e)
            {
                _logger.LogError(e, "Nie udało się zmienić stanu eliminacji.");
                return Json(new { ok = false, message = "Nie udało się zmienić stanu eliminacji. Spróbuj ponownie." });
            }
        }
        
        [Route("aktualizuj-status-fun-user")]
        public IActionResult UpdateFunUser(ApplicationUser model)
        {
            try
            {
                _adminService.UpdateFunUser(model);
                return Json(new { ok = true });
            }
            catch (Exception e)
            {
                _logger.LogError(e, "Nie udało się zmienić statusu Fun Account.");
                return Json(new { ok = false, message = "Nie udało się zmienić statusu Fun Account.. Spróbuj ponownie." });
            }
        }

        [Route("usun-uzytkownika")]
        public IActionResult DeleteUser(string id, bool delete)
        {
            try
            {
                if (!delete) return Json(new {ok = false, message = "Czy na pewno chcesz usunąć tego użytkownika ?"});
                _adminService.DeleteUser(id);
                return Json(new {ok = true});
            }
            catch (Exception e)
            {
                _logger.LogError(e, "Nie udało się usunąć użytkownika.");
                return Json(new { ok = false, message = "Nie udało się usunąć użytkownika.. Spróbuj ponownie." });
            }
        }
        #endregion
        
    }
}

BetWorldCup/Controllers/ChatController.cs
using BetWorldCup.Models;
using BetWorldCup.Services;
using Microsoft.AspNetCore.Mvc;

namespace BetWorldCup.Controllers
{
    public class ChatController : Controller
    {
        private readonly IChatService _chatService;

        public ChatController(IChatService chatService)
        {
            _chatService = chatService;
        }
        
        public EmptyResult InsertChatMessage(ChatRow model)
        {
            _chatService.AddMessage(model);
            return new EmptyResult();
        }

        public JsonResult GetChatMessages()
        {
            return Json(_chatService.GetChatMessages());
        }
    }
}

BetWorldCup/Controllers/DocsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace BetWorldCup.Controllers
{
    [AllowAnonymous]
    public class DocsController : Controller
    {
        [Route("regulamin")]
        public IActionResult Rules()
        {
            return View();
        }

        [Route("polityka-prywatnosci")]
        public IActionResult PrivacyPolicy()
        {
            return View();
        }
    }
}

BetWorldCup/Views/Shared/_Chat.cshtml
<div class="row">
    <div class="col-11">
        <div class="daily-feeds card div--card">
            <div class="card-header">
                <h3 class="h4">Witamy na czacie:</h3>
                @Html.Hidden("appname", User.AppName())
                @Html.Hidden("UrlAddMessage", Url.Action("InsertChatMessage", "Chat"))
                @Html.Hidden("GetChatMessages", Url.Action("GetChatMessages", "Chat"))
            </div>
            <div class="card-body no-padding card--body" id="scrollDown">
                <!-- Item-->
                <div class="item">
                    <div class="feed d-flex justify-content-between">
                        <div class="feed-body d-flex justify-content-between item--body">
                            <div class="content item--body__content">
                                <div id="logins"></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="input-group">
            <textarea id="MessageField" name="MessageField[0]" class="input-material card card--input" placeholder="Napisz wiadomość..."></textarea>
            <button id="sendmes" class="card card--btn">
                <i class="fa fa-paper-plane" aria-hidden="true"></i>
            </button>
        </div>
        
    </div>
</div>

BetWorldCup/Views/Shared/_GoogleAnalytics.cshtml
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-118761608-1"></script>
<script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'UA-118761608-1');
</script>

BetWorldCup/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    @Html.Partial("_GoogleAnalytics")
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - Bet World Cup</title>
    <link rel="shortcut icon" href="~/img/favicon.ico"/>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/lib/tether/dist/css/tether.css" />
        <link rel="stylesheet" href="~/lib/toastr.js/toastr.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
        <link rel="stylesheet" href="~/lib/tether/dist/css/tether.min.css" />
        <link rel="stylesheet" href="~/lib/toastr.js/toastr.min.css" />
    </environment>

    <!-- Google fonts - Roboto -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poppins:300,400,700">
    <!-- theme stylesheet-->
    <link rel="stylesheet" href="~/css/style.blue.css" id="theme-stylesheet">
    <!-- Custom stylesheet - for your changes-->
    <link rel="stylesheet" href="~/css/custom_20180627.css">
    <!-- Media Queries-->
    <link href="~/css/media_20180626.css" rel="stylesheet" />
    <!-- Font Awesome CDN-->
    <link href="~/lib/font-awesome/css/font-awesome.css" rel="stylesheet" />
    <!-- Chat stylesheet & scripts -->
    <link href="~/css/chat.css" rel="stylesheet" />
    <!-- Cookies stylesheet & scripts-->
    <link rel="stylesheet" href="~/css/accept-cookies.css" />
    
    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/tether/dist/js/tether.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/scripts/chat_28062018.js"></script>
        <script src="~/scripts/cookiepopup.js"></script>
        <script src="~/lib/chart.js/Chart.js"></script>
        <script src="~/scripts/front.js"></script>
        <script src="~/lib/toastr.js/toastr.min.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/tether/dist/js/tether.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
        <script src="~/lib/chart.js/Chart.min.js"></script>
        <script src="~/scripts/chat_28062018.js"></script>
        <script src="~/scripts/front.js"></script>
        <script src="~/scripts/cookiepopup.js"></script>
        <script src="~/lib/toastr.js/toastr.min.js"></script>
    </environment>

</head>
<body>
    <div class="page">
        <header class="header">
            @Html.Partial("_Navbar")
        </header>
        <div class="page-content d-flex align-items-stretch">
            <nav class="side-navbar chat">
                <!-- Sidebar Header-->
                <div class="sidebar-header d-flex align-items-center">
                    <div class="icon bg-black" id="chat-btn"><i class="fa fa-comments fa-2x"></i></div>
                    <div class="title">
                        <h1 class="h4">Czat</h1>
                    </div>
                </div>

                <div class="style-switch">
                    <div class="styleChat">
                        @Html.Partial("_Chat")
                    </div>
                </div>

            </nav>
            <div class="content-inner">
                @RenderBody()

                <footer class="main-footer">
                    <div class="container-fluid">
                        <div class="row">
                            <div class="col-sm-6">
                                <p>
                                    Project by: <a href="mailto:ivaan84@gmail.com">ivIT</a>, <a href="mailto:jakubkaczmarek92@gmail.com">JKaczmarek</a>, <a href="mailto:marek.szupienko@gmail.com">MSzupieńko</a>
                                </p>
                            </div>
                            <div class="col-sm-6 text-right">
                                <p>
                                    Theme by: <a href="https://bootstrapious.com/admin-templates">Bootstrapious</a>
                                </p>
                            </div>
                        </div>
                    </div>
                </footer>
            </div>
            <nav class="right-sidebar">
                <div class="sidebar-header d-flex align-items-center">
                    <div class="icon bg-black"><a id="right-sidebar--stats" href="#"><i class="fa fa-bar-chart fa-2x"></i></a></div>
                    <div class="title">
                        <h1 class="h4">Tabela</h1>
                    </div>
                </div>
                <div class="col-12" id="legend">
                    @Html.Partial("~/Views/Stats/Tables/_Legend.cshtml")
                </div>
                <div id="right-sidebar--stats__table" class="col-md-12">
                    @Html.RenderAction("FullClassificationTable", "Stats", "", new { overflow = true })
                </div>
            </nav>
        </div>
    </div>

    @RenderSection("Scripts", required: false)
    @* ReSharper disable once Mvc.ViewComponentNotResolved *@
    @await Component.InvokeAsync("NToastNotify")
</body>
</html>

BetWorldCup/Views/Shared/_LayoutAccount.cshtml
<!DOCTYPE html>
<html>
<head>
    @Html.Partial("_GoogleAnalytics")
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - Bet World Cup</title>
    <link rel="shortcut icon" href="~/img/favicon.ico" />

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css"/>
        <link rel="stylesheet" href="~/lib/tether/dist/css/tether.css"/>
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
        <link rel="stylesheet" href="~/lib/tether/dist/css/tether.min.css"/>
    </environment>

    <!-- Google fonts - Roboto -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poppins:300,400,700">
    <!-- theme stylesheet-->
    <link rel="stylesheet" href="~/css/style.blue.css" id="theme-stylesheet">
    <!-- Custom stylesheet - for your changes-->
    <link rel="stylesheet" href="~/css/custom_20180627.css">
    <!-- Media Queries-->
    <link href="~/css/media_20180626.css" rel="stylesheet" />
    <!-- Font Awesome CDN-->
    <link href="~/lib/font-awesome/css/font-awesome.css" rel="stylesheet"/>

</head>
<body>
    <!-- Page Body-->
    <div class="page login-page">
        <div class="container d-flex align-items-center">
            <div class="form-holder has-shadow">
                <div class="row">
                    @RenderBody()
                </div>
            </div>
        </div>
        <!-- Page Footer-->
        <div class="copyrights text-center">
            <p>
                Project by: <a href="mailto:ivaan84@gmail.com">ivIT</a>, <a href="mailto:jakubkaczmarek92@gmail.com">JKaczmarek</a>, <a href="mailto:marek.szupienko@gmail.com">MSzupieńko</a>
            </p>
        </div>
    </div>
    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/tether/dist/js/tether.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/scripts/front.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/tether/dist/js/tether.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
        <script src="~/scripts/front.js"></script>
    </environment>

    @RenderSection("Scripts", required: false)
    @* ReSharper disable once Mvc.ViewComponentNotResolved *@
    @await Component.InvokeAsync("NToastNotify")
</body>
</html>

BetWorldCup/Views/Shared/_Navbar.cshtml
@using System.Security.Claims
@{
    var claimsIdentity = (ClaimsIdentity)User.Identity;
    var claim = claimsIdentity.FindFirst(ClaimTypes.GivenName);
    var userName = claim.Value;
}

<nav class="navbar">
    <div class="container-fluid">
        <div class="navbar-holder d-flex align-items-center justify-content-between">
            <!-- Navbar Header-->
            <div class="navbar-header">
                <!-- Navbar Brand -->
                <a href="@Url.Action("Index", "Home")" class="navbar-brand">
                    <div class="brand-text brand-big"><span>Bet </span><strong>WorldCup</strong></div>
                    <div class="brand-text brand-small"><strong>BWC</strong></div>
                </a>
            </div>

            <!-- Navbar Menu Logout-->
            <ul class="nav-menu list-unstyled d-flex flex-md-row align-items-md-center">
                <!-- Admin Menu  -->
            @if (User.IsInRole("ADMIN"))
            {
                <li class="nav-item dropdown">
                    <a id="adminMenuDropdown" rel="nofollow" href="" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" class="nav-link language dropdown-toggle">
                        <i class="fa fa-bars"></i> <span id="" class="d-none d-sm-inline-block">Panel Administratora</span>
                    </a>
                    <ul aria-labelledby="menuDropdown" class="dropdown-menu">
                        <li><a asp-controller="Admin" asp-action="Index" class="dropdown-item"><i class="fa fa-futbol-o"></i> Wyniki</a></li>
                        <li><a asp-controller="Admin" asp-action="ListOfMatches" class="dropdown-item"><i class="fa fa-address-book-o"></i> Mecze</a></li>
                        <li><a asp-controller="Admin" asp-action="Teams" class="dropdown-item"><i class="fa fa-calendar-o"></i> Drużyny</a></li>
                        <li><a asp-controller="Admin" asp-action="Users" class="dropdown-item"><i class="fa fa-user-o"></i> Użytkownicy</a></li>
                        <li><a asp-controller="Admin" asp-action="DeleteUsers" class="dropdown-item"><i class="fa fa-user-o"></i> Usuwanie użytkowników</a></li>
                        <li><a asp-controller="Admin" asp-action="GoogleAnalytics" class="dropdown-item"><i class="fa fa-bar-chart-o"></i> Statystyki Google</a></li>
                    </ul>
                </li>
            }
                <!-- Menu    -->
                <li class="nav-item dropdown">
                    <a id="menuDropdown" rel="nofollow" href="" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" class="nav-link language dropdown-toggle">
                        <i class="fa fa-bars"></i> <span id="" class="d-none d-sm-inline-block">Menu</span>
                    </a>
                    <ul aria-labelledby="menuDropdown" class="dropdown-menu">
                        <li><a asp-controller="Home" asp-action="Index" class="dropdown-item"><i class="fa fa-home"></i> Strona główna</a></li>
                        <li><a asp-controller="Home" asp-action="AllMatches" class="dropdown-item"><i class="fa fa-futbol-o"></i> Wszystkie mecze</a></li>
                        <li><a asp-controller="Stats" asp-action="ResultAllStats" class="dropdown-item"><i class="fa fa-bar-chart-o"></i> Statystyki</a></li>
                        <li><a asp-controller="Docs" asp-action="Rules" class="dropdown-item"><i class="fa fa-book"></i> Regulamin</a></li>
                        <li><a asp-controller="Stats" asp-action="UserData" asp-route-user="@userName" class="dropdown-item"><i class="fa fa-user-o"></i> Twoje dane</a></li>
                        <li><a asp-controller="Account" asp-action="ChangePassword" class="dropdown-item"><i class="fa fa-key"></i> Zmień hasło</a></li>

                    </ul>
                </li>
                <!-- Logout    -->
                <li class="nav-item">
                    <a class="nav-link nav-link--help" 
                       data-toggle="tooltip"
                       data-placement="bottom"
                       title="Napisz do nas jeśli coś Ci nie działa!"
                       href="mailto:support@betworldcup.pl" alt="">
                        <i class="fa fa-question"></i>
                    </a>
                </li>
                <li class="nav-item hidden-sm-down">
                    <a asp-controller="Account" asp-action="Logout" class="nav-link logout">
                        Wyloguj <i class="fa fa-sign-out"></i>
                    </a>
                </li>
                <li class="nav-item hidden-sm-up">
                    <a asp-controller="Account" asp-action="Logout" class="nav-link logout">
                        <i class="fa fa-sign-out"></i>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>

@section Scripts {
    @await Html.PartialAsync("_ValidationScriptsPartial")
}